server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/lalozouter/spring-cloud-config-store
          uri: https://github.com/lalozouter/rentcarBestPractices.git
          search-paths:
          #- '*service'
          - 'service-config/*service'  